"""chats schemas

Revision ID: 6744bae4f020
Revises: f875a3ef9ce5
Create Date: 2026-04-01 12:21:49.250229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6744bae4f020'
down_revision: Union[str, None] = 'f875a3ef9ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_members',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_chat_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_chat_id'], ['group_chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_chat_id', name='uix_user_group')
    )
    op.create_table('personal_chats',
    sa.Column('user1_id', sa.UUID(), nullable=True),
    sa.Column('user2_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user1_id', 'user2_id', name='uix_user1_user2')
    )
    op.add_column('messages', sa.Column('personal_chat_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('group_chat_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'messages', 'group_chats', ['group_chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'personal_chats', ['personal_chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'group_chat_id')
    op.drop_column('messages', 'personal_chat_id')
    op.drop_table('personal_chats')
    op.drop_table('chat_members')
    op.drop_table('group_chats')
    # ### end Alembic commands ###
